version: '3'
services:
  app: 
    container_name: stocomm
    build: .
    ports:
      - 3000:3000
    environment:
      - SQL_PASSWORD=kker
      - SQL_ACCOUNT=root
      - SQL_DATABASE=stocomm
      - SQL_HOST=mysql
      - SQL_PORT=3306
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - PORT=3000
      - MODE=dev
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kker
      - MYSQL_PASSWORD=kker
      - MYSQL_USER=king
      - MYSQL_DATABASE=stocomm
    volumes:
      - /mnt/c/Users/kao/mnt-mysql/stocomm.sql:/docker-entrypoint-initdb.d/stocomm.sql:ro
    
