services:
  app: 
    container_name: stocomm
    build: .
    ports:
      - 3000:3000
    env_file:
      - dev.env
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  redis:
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 60s
      retries: 10
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kker
      - MYSQL_PASSWORD=kker
      - MYSQL_USER=king
      - MYSQL_DATABASE=stocomm
    volumes:
      - ./sqldump-for-dev/stocomm.sql:/docker-entrypoint-initdb.d/stocomm.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 60s
      retries: 10
    
